title: RLAI Lab
description: The Reinforcement Learning and Artificial Intelligence Lab
theme: jekyll-theme-time-machine
show_downloads: false

collections_dir: rlai_collections

collections:
  - publications
  - people