title: RLAI Lab
description: The Reinforcement Learning and Artificial Intelligence Lab
theme: jekyll-theme-time-machine
show_downloads: false

defaults:
  - scope:
      path: "_publications/"
    values:
      arepubs: true