title: RLAI Lab
description: The Reinforcement Learning and Artificial Intelligence Lab
theme: jekyll-theme-time-machine
show_downloads: false
url: https://rlai-lab.github.io

collections_dir: rlai_collections

collections:
  - publications
  - people